//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestExtensions.FluentBDD.Processors.Reporters.HTML {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HtmlResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HtmlResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestExtensions.FluentBDD.Processors.Reporters.HTML.HtmlResources", typeof(HtmlResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to body
        ///{
        ///	max-width:100%;
        ///	background-color:#fff;
        ///	font-family: Verdana, Arial, Helvetica, sans-serif;
        ///	font-size: 10pt;
        ///	margin: 0;
        ///	padding: 0;
        ///    padding-bottom:40px;
        ///}
        ///
        ///ul
        ///{
        ///    padding:5px;
        ///    margin:5px;
        ///    border:1px solid #d0d0d0;
        ///    background-color:#f0f0f0;
        ///    -webkit-border-radius: 10px;
        ///    -moz-border-radius:    10px;
        ///    border-radius:10px;
        ///}
        ///
        ///li
        ///{
        ///    list-style-type: none;
        ///}
        ///			
        ///#main
        ///{
        ///	width: 100%;
        ///	height:100%;
        ///}
        ///			
        ///.header, .footer
        ///{
        ///    background: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BDD_css {
            get {
                return ResourceManager.GetString("BDD_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $(function () {
        ///    $(&apos;.canToggle&apos;).each(function () {
        ///        var target = $(&apos;#&apos; + $(this).data(&apos;toggle-target&apos;));
        ///        target.hide();
        ///        $(this).click(function () {
        ///            target.toggle(200);
        ///        });
        ///    });
        ///
        ///    $(&apos;.expandAll&apos;).click(function () {
        ///        $(&apos;.steps&apos;).css(&apos;display&apos;, &apos;&apos;);
        ///    });
        ///    $(&apos;.collapseAll&apos;).click(function () {
        ///        $(&apos;.steps&apos;).css(&apos;display&apos;, &apos;none&apos;);
        ///    });
        ///
        ///    $(&quot;ul.resultSummary li:not(&apos;.storySummary&apos;):not(&apos;.scenarioSummary&apos;)&quot;)
        ///        .a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BDD_js {
            get {
                return ResourceManager.GetString("BDD_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! jQuery v1.7.1 jquery.com | jquery.org/license */
        ///(function(a,b){function cy(a){return f.isWindow(a)?a:a.nodeType===9?a.defaultView||a.parentWindow:!1}function cv(a){if(!ck[a]){var b=c.body,d=f(&quot;&lt;&quot;+a+&quot;&gt;&quot;).appendTo(b),e=d.css(&quot;display&quot;);d.remove();if(e===&quot;none&quot;||e===&quot;&quot;){cl||(cl=c.createElement(&quot;iframe&quot;),cl.frameBorder=cl.width=cl.height=0),b.appendChild(cl);if(!cm||!cl.createElement)cm=(cl.contentWindow||cl.contentDocument).document,cm.write((c.compatMode===&quot;CSS1Compat&quot;?&quot;&lt;!doctype html&gt;&quot;:&quot;&quot;)+&quot;&lt;html&gt;&lt;body [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_1_7_1_min {
            get {
                return ResourceManager.GetString("jquery_1_7_1_min", resourceCulture);
            }
        }
    }
}
